# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localice < Formula
  desc ""
  homepage ""
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vknabel/localice/releases/download/v0.0.3/localice_0.0.3_Darwin_arm64.tar.gz"
      sha256 "eaabdcf76d18e08dc6e6d0d7ec2efb8a2b5b28335ed27273f32435be2390075f"

      def install
        bin.install "localice"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/localice/releases/download/v0.0.3/localice_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "0ea71158afefe42dc22b44f13c95de5835b42630210e6b6a344c6d495c5ddacc"

      def install
        bin.install "localice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vknabel/localice/releases/download/v0.0.3/localice_0.0.3_Linux_arm64.tar.gz"
      sha256 "a61d0da431c05483970bec6ddb7caf0f269154dd37098c7294be69847362a557"

      def install
        bin.install "localice"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/localice/releases/download/v0.0.3/localice_0.0.3_Linux_x86_64.tar.gz"
      sha256 "0f7dbe77d62765ab71651b67effbe15ae6e64c3dac44af940a694422156cdae0"

      def install
        bin.install "localice"
      end
    end
  end
end
