# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localice < Formula
  desc ""
  homepage ""
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vknabel/localice/releases/download/v0.0.2/localice_0.0.2_Darwin_arm64.tar.gz"
      sha256 "575ea00e29de0d569da58efd70a580a6dec5500a299b5fed89d6f9f901912f17"

      def install
        bin.install "localice"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/localice/releases/download/v0.0.2/localice_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "7e2005e533c6ebc353052f67accda71b5f05b9a94759d0ac9807fc1824e3e802"

      def install
        bin.install "localice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vknabel/localice/releases/download/v0.0.2/localice_0.0.2_Linux_arm64.tar.gz"
      sha256 "a007d64ccfff11191520bd61ddea505268d8eaa7c1ae72207ca0ba61cf88a771"

      def install
        bin.install "localice"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/localice/releases/download/v0.0.2/localice_0.0.2_Linux_x86_64.tar.gz"
      sha256 "752b92c387b57d4ded1a49f9b30a3773dffa2e32756d4bff7f5ce8de72ab091f"

      def install
        bin.install "localice"
      end
    end
  end
end
