# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localice < Formula
  desc ""
  homepage ""
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vknabel/localice/releases/download/v0.0.4/localice_0.0.4_Darwin_arm64.tar.gz"
      sha256 "884e824241373d5e2df8411097f56d2daca1f6f10ecf0748822b295ff5bbd205"

      def install
        bin.install "localice"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/localice/releases/download/v0.0.4/localice_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "4e6feec9e81a7fe7c57da62d59e7957bdfe9dddf4a67f6c8587c00fad37a4f24"

      def install
        bin.install "localice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vknabel/localice/releases/download/v0.0.4/localice_0.0.4_Linux_arm64.tar.gz"
      sha256 "9b682127492657da6905a5e5b18a3723b29919d00a4ddff161999cc0f4b89d9c"

      def install
        bin.install "localice"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/localice/releases/download/v0.0.4/localice_0.0.4_Linux_x86_64.tar.gz"
      sha256 "f5a32f552067a73906a788338181768aa4d8f832fd218de8a76c2c3ee784375a"

      def install
        bin.install "localice"
      end
    end
  end
end
