# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puffery < Formula
  desc ""
  homepage ""
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vknabel/go-puffery/releases/download/v0.1.1/go-puffery_0.1.1_Darwin_arm64.tar.gz"
      sha256 "f98623a541d2ea929b265d458a3c44f61d1661386c6407ab4792b3a42fbf2835"

      def install
        bin.install "puffery"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/go-puffery/releases/download/v0.1.1/go-puffery_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "3b105beb91acbbfb4d89d5f1904de453f3fc39c092807dcea7d2403c27cbdfa2"

      def install
        bin.install "puffery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vknabel/go-puffery/releases/download/v0.1.1/go-puffery_0.1.1_Linux_arm64.tar.gz"
      sha256 "37ff7273e24f35ea931f4d164679e197600c18feb13b340b9a76f6791d085167"

      def install
        bin.install "puffery"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/go-puffery/releases/download/v0.1.1/go-puffery_0.1.1_Linux_x86_64.tar.gz"
      sha256 "a211f9fb1589d4f0212d1208c5d885323dded79a93523a47fb36810bed93b522"

      def install
        bin.install "puffery"
      end
    end
  end
end
