# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puffery < Formula
  desc ""
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vknabel/go-puffery/releases/download/v0.1.0/go-puffery_0.1.0_Darwin_arm64.tar.gz"
      sha256 "8e33c500e0c70630f31d830dafde892eb6216044bbeeec9bf2eca455c28aa1fd"

      def install
        bin.install "puffery"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/go-puffery/releases/download/v0.1.0/go-puffery_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "ba19f12b73cae812a280db579120b6c7c8217e28bf4f60862d9ea1f5dd8b781c"

      def install
        bin.install "puffery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vknabel/go-puffery/releases/download/v0.1.0/go-puffery_0.1.0_Linux_arm64.tar.gz"
      sha256 "5001bbe2f4d231eebc92649f9e68b233000d1b181aa4c41b92c0b2ae60df1bab"

      def install
        bin.install "puffery"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/go-puffery/releases/download/v0.1.0/go-puffery_0.1.0_Linux_x86_64.tar.gz"
      sha256 "d8b0ae1f0c007b0a49dfcf9fb15c9a0f859f256bd8f16b64403c4fac8a75bac6"

      def install
        bin.install "puffery"
      end
    end
  end
end
